import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh';

interface Translations {
  [key: string]: {
    [key in Language]: string;
  };
}

export const translations: Translations = {
  // Global / App
  appName: { en: 'MockDev Platform', zh: 'MockDev 平台' },
  appBrand: { en: 'MockDev', zh: 'MockDev' },
  appTagline: { en: 'Enterprise Mock Platform', zh: '企业级 Mock 平台' },
  moduleUnderDevelopment: { en: 'Module under development', zh: '模块开发中' },
  moduleComingSoon: {
    en: 'This feature will be available in the next release.',
    zh: '该功能将在下一个版本中提供。',
  },

  // Sidebar
  dashboard: { en: 'Dashboard', zh: '仪表盘' },
  apis: { en: 'API Management', zh: '接口管理' },
  proxies: { en: 'Proxy Rules', zh: '代理规则' },
  assets: { en: 'Public Assets', zh: '公共资产' },
  team: { en: 'Team Members', zh: '团队成员' },
  stats: { en: 'Analytics', zh: '统计分析' },
  settings: { en: 'Settings', zh: '设置' },
  projects: { en: 'Projects', zh: '项目管理' },

  // Auth
  login: { en: 'Login', zh: '登录' },
  register: { en: 'Register', zh: '注册' },
  acceptingInvite: { en: 'Accepting invite...', zh: '正在接受邀请...' },
  inviteTitle: { en: 'Project Invitation', zh: '项目邀请' },
  inviteDesc: {
    en: 'You were invited to join a MockHub project.',
    zh: '你被邀请加入一个 MockHub 项目。',
  },
  inviteInvalid: { en: 'Invitation unavailable or expired.', zh: '邀请不可用或已过期。' },
  inviteEmailMismatch: {
    en: 'Please use the invited email address to accept.',
    zh: '请使用被邀请的邮箱接受邀请。',
  },
  inviteLockedInfo: {
    en: 'Email and company are locked by this invitation.',
    zh: '邮箱和公司名称已由邀请锁定。',
  },
  acceptInviteCreateAccount: {
    en: 'Accept invite and create account',
    zh: '接受邀请并创建账号',
  },
  email: { en: 'Email', zh: '邮箱' },
  password: { en: 'Password', zh: '密码' },
  username: { en: 'Username', zh: '用户名' },
  company: { en: 'Company', zh: '公司名称' },
  companyPlaceholder: { en: 'Acme Corp', zh: '示例公司' },
  usernamePlaceholder: { en: 'johndoe', zh: '张三' },
  emailPlaceholder: { en: 'name@company.com', zh: 'name@company.com' },
  noAccount: { en: "Don't have an account?", zh: '没有账号？' },
  hasAccount: { en: 'Already have an account?', zh: '已有账号？' },
  welcomeBack: { en: 'Welcome Back', zh: '欢迎回来' },
  createAccount: { en: 'Create Account', zh: '创建账号' },

  // Dashboard
  totalApis: { en: 'Total APIs', zh: '接口总数' },
  activeProxies: { en: 'Active Proxies', zh: '活跃代理' },
  requestsHr: { en: 'Requests/hr', zh: '请求数/小时' },
  recentActivity: { en: 'Recent Activity', zh: '最近动态' },
  systemStatus: { en: 'System Status', zh: '系统状态' },
  viewAll: { en: 'View All', zh: '查看全部' },
  activityExample: {
    en: 'Alex Chen updated mock data for /api/v1/user',
    zh: 'Alex Chen 更新了 /api/v1/user 的 Mock 数据',
  },
  activityTimeAgo: { en: '14 minutes ago', zh: '14 分钟前' },
  statusProxyEngine: { en: 'Proxy Engine', zh: '代理引擎' },
  statusMockStorage: { en: 'Mock Storage', zh: 'Mock 存储' },
  statusAuthService: { en: 'Auth Service', zh: '认证服务' },
  statusOperational: { en: 'OPERATIONAL', zh: '运行正常' },
  statusLatency: { en: 'LATENCY', zh: '延迟' },
  teamTipTitle: { en: 'Team Tip', zh: '团队小贴士' },
  teamTipDesc: {
    en: 'Use Script Mode to simulate dynamic responses like pagination or time-based tokens.',
    zh: '使用脚本模式可以模拟分页或基于时间的令牌等动态响应。',
  },
  teamTipCta: { en: 'Read Documentation', zh: '查看文档' },
  scriptMode: { en: 'Script Mode', zh: '脚本模式' },

  // Projects
  myProjects: { en: 'My Projects', zh: '我的项目' },
  createProject: { en: 'Create Project', zh: '创建项目' },
  joinProject: { en: 'Join Project', zh: '加入项目' },
  projectName: { en: 'Project Name', zh: '项目名称' },
  projectDesc: { en: 'Description', zh: '项目描述' },
  editProject: { en: 'Edit Project', zh: '编辑项目' },
  editProjectSubtitle: {
    en: 'Update project settings and configuration.',
    zh: '更新项目设置和配置。',
  },
  createProjectSubtitle: {
    en: 'Set up a new workspace for your team.',
    zh: '为团队创建新的工作空间。',
  },
  mockKey: { en: 'Mock Key', zh: 'Mock 密钥' },
  copyKey: { en: 'Copy Key', zh: '复制密钥' },
  proxyInstructions: { en: 'Proxy Instructions', zh: '代理使用说明' },
  headerRequired: { en: 'Include this key in your request headers as "x-mock-key"', zh: '在请求头中包含 "x-mock-key" 字段并填入此密钥' },
  owner: { en: 'Owner', zh: '创建人' },
  members: { en: 'Members', zh: '成员' },
  projectLogo: { en: 'Project Logo', zh: '项目 Logo' },
  projectLogoDesc: {
    en: 'Upload a custom logo for your project. Recommended size: 256x256px.',
    zh: '为项目上传自定义 Logo，推荐尺寸：256x256 像素。',
  },
  projectLogoUploading: { en: 'Uploading logo...', zh: 'Logo 上传中…' },
  projectLogoPlaceholder: {
    en: 'Or paste a logo URL here...',
    zh: '或在此粘贴 Logo 的 URL...',
  },
  projectNamePlaceholder: {
    en: 'e.g. Payment Gateway Mock',
    zh: '例如：支付网关 Mock',
  },
  projectDescPlaceholder: {
    en: 'Briefly describe the purpose of this project...',
    zh: '简单描述该项目的用途...',
  },
  initialMembers: { en: 'Initial Members', zh: '初始成员数' },
  membersJustMe: { en: 'Just me', zh: '仅我自己' },
  membersSmallTeam: { en: 'Small Team (3+)', zh: '小团队（3+）' },
  membersLargeTeam: { en: 'Large Team (10+)', zh: '大团队（10+）' },
  proxyUrl: { en: 'Proxy URL', zh: '代理地址' },
  proxyUrlPlaceholder: {
    en: 'https://proxy.example.com',
    zh: 'https://proxy.example.com',
  },
  cancel: { en: 'Cancel', zh: '取消' },
  saveCreateProject: { en: 'Create Project', zh: '创建项目' },
  saveUpdateProject: { en: 'Update Project', zh: '更新项目' },
  projectSaveError: { en: 'Network error, failed to save project', zh: '网络异常，无法保存项目' },
  projectLogoUploadError: { en: 'Network error, logo upload failed', zh: '网络异常，Logo 上传失败' },

  projectDefaultStrategy: { en: 'Default Proxy Strategy', zh: '默认代理策略' },
  projectDefaultStrategyStatic: { en: 'Static Mock', zh: '静态 Mock' },
  projectDefaultStrategyScript: { en: 'Dynamic Mock Script', zh: '动态 Mock 脚本' },
  projectDefaultStrategyProxy: { en: 'Real Service Proxy', zh: '真实服务代理' },

  enabled: { en: 'Enabled', zh: '已开启' },
  disabled: { en: 'Disabled', zh: '已关闭' },

  projectAutoCapture: { en: 'Auto Capture (Learning)', zh: '自动学习更新' },
  projectAutoCaptureHint: {
    en: 'Update endpoint docs from real traffic',
    zh: '基于真实流量更新接口文档/Mock',
  },
  cookieRewrite: { en: 'Cookie Domain Rewrite', zh: 'Cookie 域名重写' },
  cookieRewriteOff: { en: 'Off', zh: '关闭（不处理）' },
  cookieRewriteOrigin: { en: 'Rewrite to current origin', zh: '重写为当前访问域名' },
  cookieRewriteCustom: { en: 'Rewrite to custom domain', zh: '重写为自定义域名' },
  cookieRewriteDomain: { en: 'Custom cookie domain', zh: '自定义 Cookie 域名' },
  cookieRewriteDomainPlaceholder: { en: 'e.g. localhost', zh: '例如：localhost' },

  // Public Assets
  publicAssetsTitle: { en: 'Public Assets', zh: '公共资产' },
  publicAssetsDesc: {
    en: 'Shared definitions and infrastructure endpoints for your project.',
    zh: '项目中共享的定义和基础设施端点。',
  },
  publicAssetsAdd: { en: 'Add Asset', zh: '新增资产' },
  publicAssetsEdit: { en: 'Edit Asset', zh: '编辑资产' },
  publicAssetsSearchPlaceholder: { en: 'Search assets...', zh: '搜索资产...' },
  publicAssetsAssetNamePlaceholder: { en: 'Asset name', zh: '资产名称' },
  publicAssetsCategoryPlaceholder: { en: 'Category', zh: '资产类别' },
  publicAssetsSave: { en: 'Save Asset', zh: '保存资产' },
  publicAssetsSaving: { en: 'Saving...', zh: '保存中...' },
  publicAssetsLoading: { en: 'Loading assets...', zh: '资产加载中...' },
  publicAssetsValueRequired: { en: 'Name and value are required', zh: '资产名称和资产值不能为空' },
  publicAssetsJsonInvalid: { en: 'JSON asset value must be valid JSON', zh: 'JSON 资产值必须是有效 JSON' },
  publicAssetsErrorCodeRequired: { en: 'At least one error code is required', zh: '至少需要一个错误码' },
  publicAssetsUnavailable: { en: 'Assets unavailable', zh: '资产不可用' },
  publicAssetsSaveFailed: { en: 'Save failed', zh: '保存失败' },
  publicAssetsDeleteFailed: { en: 'Delete failed', zh: '删除失败' },
  publicAssetsDeleteConfirm: { en: 'Delete asset?', zh: '确定删除资产？' },
  publicAssetsTypeUrl: { en: 'Base URL', zh: '基础 URL' },
  publicAssetsTypeErrorCode: { en: 'Error Codes', zh: '错误码' },
  publicAssetsTypeEnum: { en: 'Enum Set', zh: '枚举集合' },
  publicAssetsTypeJson: { en: 'JSON Config', zh: 'JSON 配置' },
  publicAssetsTypeText: { en: 'Text Constant', zh: '文本常量' },
  publicAssetsErrorCodeItems: { en: 'Error Code Items', zh: '错误码项' },
  publicAssetsAddCode: { en: 'Add Code', zh: '新增错误码' },
  publicAssetsErrorCodePlaceholder: { en: 'ERR_001', zh: 'ERR_001' },
  publicAssetsErrorMessagePlaceholder: { en: 'Error message', zh: '错误信息' },
  publicAssetsEnumItems: { en: 'Enum Items', zh: '枚举项' },
  publicAssetsAddItem: { en: 'Add Item', zh: '新增项' },
  publicAssetsEnumItemPlaceholder: { en: 'Item', zh: '枚举项' },
  publicAssetsJsonValue: { en: 'JSON Value', zh: 'JSON 值' },
  publicAssetsFormatJson: { en: 'Format JSON', zh: '格式化 JSON' },
  publicAssetsTextPlaceholder: { en: 'Shared text value', zh: '共享文本值' },
  publicAssetsUrlPlaceholder: { en: 'https://api.example.com', zh: 'https://api.example.com' },
  publicAssetsOfficialTab: { en: 'Assets', zh: '正式资产' },
  publicAssetsSuggestionsTab: { en: 'Suggestions', zh: '建议资产' },
  publicAssetsColumnName: { en: 'Name', zh: '名称' },
  publicAssetsColumnType: { en: 'Type', zh: '类型' },
  publicAssetsColumnValue: { en: 'Value', zh: '取值' },
  publicAssetsColumnActions: { en: 'Actions', zh: '操作' },
  publicAssetsSuggestionsTitle: { en: 'Suggested Assets', zh: '建议资产' },
  publicAssetsSuggestionsDesc: {
    en: 'Generated from proxy configuration and request logs. Review before adding.',
    zh: '基于代理配置和请求日志生成，确认后再加入公共资产。',
  },
  publicAssetsSuggestionAccept: { en: 'Add Asset', zh: '加入资产' },
  publicAssetsSuggestionSource: { en: 'Source', zh: '来源' },
  publicAssetsSuggestionCount: { en: 'Count', zh: '次数' },
  publicAssetsSuggestionConfidence: { en: 'Confidence', zh: '置信度' },
  publicAssetsSuggestionEmpty: { en: 'No suggested assets yet.', zh: '暂无建议资产。' },
  publicAssetsSuggestionAcceptFailed: { en: 'Failed to add suggested asset', zh: '建议资产入库失败' },
  publicAssetsSuggestionView: { en: 'View', zh: '查看' },
  publicAssetsSuggestionIgnore: { en: 'Ignore', zh: '忽略' },
  publicAssetsSuggestionDetails: { en: 'Suggestion Details', zh: '建议资产详情' },
  publicAssetsSuggestionFullValue: { en: 'Full Value', zh: '完整取值' },
  publicAssetsSuggestionMeta: { en: 'Detection Metadata', zh: '识别信息' },
  publicAssetsSuggestionCopy: { en: 'Copy Value', zh: '复制取值' },
  assetsCategoryInfrastructure: { en: 'Infrastructure', zh: '基础设施' },
  assetsCategoryDefinitions: { en: 'Definitions', zh: '定义' },
  assetsCategorySharedConfig: { en: 'Shared Config', zh: '共享配置' },
  assetsCategoryShared: { en: 'Shared', zh: '共享' },
  assetsNameAuthEndpoint: { en: 'Auth Endpoint', zh: '认证服务地址' },
  assetsNameUserRoles: { en: 'User Roles', zh: '用户角色' },
  assetsNameErrorCodes: { en: 'Error Codes', zh: '错误码' },
  assetsNameCdnBase: { en: 'CDN Base', zh: 'CDN 基地址' },
  publicAssetsEmptyTitle: { en: 'Centralize your constants', zh: '集中管理你的常量' },
  publicAssetsEmptyDesc: {
    en: 'Define enums, base URLs, and shared schemas here to ensure consistency across all your mock endpoints.',
    zh: '在此维护枚举、基础 URL 和共享 Schema，保证所有 Mock 接口的一致性。',
  },
  mockAssetReferenceTitle: { en: 'Public Asset References', zh: '公共资产引用' },
  mockAssetCopy: { en: 'Copy asset value', zh: '复制资产值' },
  mockAssetInsert: { en: 'Insert', zh: '插入' },

  // Integration guide
  integrationGuideTitle: { en: 'Integration Guide', zh: '接入引导' },
  integrationGuideDesc: {
    en: 'Connect your frontend project to MockDev by pointing your HTTP client to the mock gateway and adding the mock key header.',
    zh: '通过将前端项目的接口请求指向 Mock 网关，并在请求头中添加 Mock 密钥，即可完成接入。',
  },
  integrationCurrentProject: { en: 'Current Project', zh: '当前项目' },
  integrationMockBaseUrl: { en: 'Mock Gateway Base URL', zh: 'Mock 网关基础地址' },
  integrationMockKeyHeader: {
    en: 'Send this key in the "x-mock-key" header for every request.',
    zh: '在每一次请求的 "x-mock-key" 请求头中携带该密钥。',
  },
  integrationHowItWorksTitle: { en: 'How it works', zh: '工作原理' },
  integrationHowItWorksStep1: {
    en: 'Your frontend sends all API requests to the MockDev gateway instead of the real backend.',
    zh: '你的前端将所有接口请求发送到 MockDev 网关，而不是直接请求真实后端。',
  },
  integrationHowItWorksStep2: {
    en: 'MockDev identifies the project by the mock key and decides whether to mock or proxy the request.',
    zh: 'MockDev 通过 Mock 密钥识别项目，再根据配置决定是返回 Mock 数据还是转发真实请求。',
  },
  integrationHowItWorksStep3: {
    en: 'You can control the behavior per endpoint in the console (static mock / script / real proxy).',
    zh: '你可以在控制台为每个接口配置静态 Mock、脚本 Mock 或真实代理。',
  },
  integrationCodeExamplesTitle: { en: 'Code examples', zh: '接入示例' },
  integrationAxiosTitle: { en: 'Axios (React / Vue)', zh: 'Axios（React / Vue 通用）' },
  integrationFetchTitle: { en: 'Native fetch', zh: '原生 fetch' },
  integrationViteTitle: { en: 'Vite dev proxy', zh: 'Vite 本地开发代理' },
  integrationNextTitle: { en: 'Next.js middleware', zh: 'Next.js 中间件接入' },
  integrationCopySnippet: { en: 'Copy snippet', zh: '复制示例代码' },

  // Selectable input
  selectableSearchPlaceholder: { en: 'Search...', zh: '搜索...' },
  selectableNoMatch: { en: 'No matches found.', zh: '未找到匹配项。' },
  selectableUseValue: { en: 'Use "{value}"', zh: '使用 “{value}”' },

  // API Table / Interface management
  interfacesTitle: { en: 'Interfaces', zh: '接口列表' },
  interfacesSearchPlaceholder: { en: 'Search APIs...', zh: '搜索接口...' },
  interfacesNew: { en: 'New Interface', zh: '新建接口' },
  basicInfoTitle: { en: 'Basic Information', zh: '基础信息' },
  interfaceNameLabel: { en: 'Interface Name', zh: '接口名称' },
  endpointPathLabel: { en: 'Endpoint Path', zh: '接口路径' },
  responseModeLabel: { en: 'Response Mode', zh: '响应模式' },
  responseModeStatic: { en: 'Static Mock', zh: '静态 Mock' },
  responseModeScript: { en: 'Dynamic Script', zh: '动态脚本' },
  responseModeProxy: { en: 'Real Proxy', zh: '真实代理' },
  proxyUrlSelectPlaceholder: {
    en: 'Select or enter target URL...',
    zh: '选择或输入目标 URL...',
  },
  tabsHeaders: { en: 'Headers', zh: '请求头' },
  tabsParams: { en: 'Request Params', zh: '请求参数' },
  tabsResponseHeaders: { en: 'Response Headers', zh: '响应头' },
  tabsResponse: { en: 'Response', zh: '响应结构' },
  tabsMock: { en: 'Mock', zh: 'Mock 配置' },
  schemaQueryTitle: { en: 'Query Parameters Schema', zh: '查询参数结构' },
  schemaBodyTitle: {
    en: 'Request Body Schema (JSON)',
    zh: '请求体结构（JSON）',
  },
  schemaAddField: { en: 'Add Field', zh: '新增字段' },
  schemaFieldName: { en: 'Field Name', zh: '字段名' },
  schemaType: { en: 'Type', zh: '类型' },
  schemaRequired: { en: 'Required', zh: '必填' },
  schemaDescription: { en: 'Description', zh: '说明' },
  schemaViewTable: { en: 'Table View', zh: '表格视图' },
  schemaViewJson: { en: 'JSON View', zh: 'JSON 视图' },
  schemaJsonInvalid: {
    en: 'Invalid JSON format, please check.',
    zh: 'JSON 格式有误，请检查后重试。',
  },
  schemaJsonFormat: { en: 'Format JSON', zh: '格式化 JSON' },
  schemaJsonPreview: { en: 'Highlighted Preview', zh: '高亮预览' },
  schemaJsonSynced: {
    en: 'Auto-synced from table view.',
    zh: '已自动从表格视图同步。',
  },
  schemaJsonDirty: {
    en: 'JSON modified. Blur to validate and apply.',
    zh: 'JSON 已修改，失焦后校验并应用。',
  },
  schemaJsonApplied: {
    en: 'JSON validated and applied.',
    zh: 'JSON 校验通过并已应用。',
  },
  headersRequestTitle: { en: 'Request Headers', zh: '请求头' },
  headersKey: { en: 'Key', zh: '键名' },
  headersValue: { en: 'Value', zh: '取值' },
  responseHeadersTitle: { en: 'Response Headers', zh: '响应头' },
  responseSchemaTitle: { en: 'Response Schema', zh: '响应结构' },
  responseSchemaField: { en: 'Field', zh: '字段' },
  responseSchemaDescShort: { en: 'Desc', zh: '说明' },
  mockStaticPreviewTitle: { en: 'Static JSON Preview', zh: '静态 JSON 预览' },
  mockProxyBadge: { en: 'Proxy Mode Active', zh: '代理模式已启用' },
  mockProxyTitle: { en: 'Proxy Mode Active', zh: '代理模式已启用' },
  mockProxyDesc: {
    en: 'This interface is currently configured to forward requests to',
    zh: '该接口当前将请求转发至',
  },
  mockProxySwitchToMock: {
    en: 'Switch to Mock Mode',
    zh: '切换到 Mock 模式',
  },
  mockProxyRun: { en: 'Run Interface', zh: '运行接口' },
  mockProxyRequestTitle: { en: 'Real Request', zh: '真实请求' },
  mockProxyRequestUrl: { en: 'Request URL', zh: '请求地址' },
  mockProxyRequestMethod: { en: 'Method', zh: '请求方法' },
  mockProxyRequestQuery: { en: 'Query Params', zh: '查询参数' },
  mockProxyRequestBody: { en: 'Request Body', zh: '请求体' },
  mockProxySend: { en: 'Send Request', zh: '发送请求' },
  mockProxySending: { en: 'Sending...', zh: '请求中...' },
  mockProxyResponseTitle: { en: 'Real Response', zh: '真实响应' },
  mockProxyResponseStatus: { en: 'Status', zh: '状态码' },
  mockProxyResponseData: { en: 'Response Body', zh: '响应数据' },
  mockProxySaveStatic: { en: 'Save as Static Mock', zh: '保存为静态 Mock' },
  mockProxySaveSuccess: {
    en: 'Saved current response as static mock.',
    zh: '已将当前响应保存为静态 Mock。',
  },
  mockProxyRequestError: {
    en: 'Real proxy request failed.',
    zh: '真实代理请求失败。',
  },
  mockProxyNoResponse: {
    en: 'No response yet. Send a real request first.',
    zh: '暂无响应数据，请先发送真实请求。',
  },
  mockProxyApplySchema: {
    en: 'Detected response headers and schema.',
    zh: '已自动解析响应头和响应结构。',
  },
  mockProxyUseTabsHint: {
    en: 'Edit request headers and params in the existing tabs, then send the request from the proxy URL area.',
    zh: '请求头、请求参数与响应结构均复用现有 Tab 维护，请在代理地址区域直接发送请求。',
  },
  jsonLargeModeHint: {
    en: 'Large content detected. Switched to lightweight rendering mode.',
    zh: '检测到大体量内容，已切换为轻量渲染模式。',
  },
  mockDynamicTitle: {
    en: 'Dynamic Mock Script (Node.js)',
    zh: '动态 Mock 脚本（Node.js）',
  },
  mockDynamicLive: { en: 'Live Execution', zh: '实时执行' },
  mockNoSelectionTitle: {
    en: 'No Interface Selected',
    zh: '未选择接口',
  },
  mockNoSelectionDesc: {
    en: 'Select an interface from the left to view or edit details.',
    zh: '在左侧选择一个接口以查看或编辑详情。',
  },
  interfaceUpdatedAgo: {
    en: 'Updated 2h ago',
    zh: '2 小时前更新',
  },
  interfaceSaveChanges: { en: 'Save Changes', zh: '保存修改' },
  apisNoProject: { en: 'No project selected', zh: '未选择项目' },
  apisSelectProject: { en: 'Select a project in the header to manage APIs.', zh: '请在顶部选择一个项目以管理接口。' },
  apisLoading: { en: 'Loading...', zh: '加载中...' },
  apisEmpty: { en: 'No interfaces yet', zh: '暂无接口' },
  apisEmptyHint: { en: 'Click "New Interface" to add one.', zh: '点击「新建接口」添加。' },
  lastCallNever: { en: 'Never', zh: '从未' },
  apiNewTitle: { en: 'New Interface', zh: '新建接口' },
  apiNewName: { en: 'Name', zh: '名称' },
  apiNewPath: { en: 'Path', zh: '路径' },
  apiCreate: { en: 'Create', zh: '创建' },
  saveSuccess: { en: 'Saved', zh: '已保存' },
  deleteSuccess: { en: 'Deleted', zh: '已删除' },

  // Proxy config
  proxyGroupsTitle: { en: 'Proxy Groups', zh: '代理分组' },
  proxyGroupsDesc: {
    en: 'Manage regex-based routing and automatic mock generation.',
    zh: '管理基于正则的路由和自动 Mock 生成。',
  },
  proxyGroupsAdd: { en: 'Add Group', zh: '新增分组' },
  proxyAutoSave: { en: 'Auto-save', zh: '自动保存' },
  proxyAutoSaveOn: { en: 'On', zh: '开' },
  proxyAutoSaveOff: { en: 'Off', zh: '关' },
  proxyRulesCount: { en: 'Rules', zh: '条规则' },
  proxyGlobalTitle: { en: 'Global Proxy Server', zh: '全局代理服务' },
  proxyGlobalDesc: {
    en: 'Your project proxy is active at:',
    zh: '项目代理服务已启动，地址为：',
  },
  proxyCopyUrl: { en: 'Copy URL', zh: '复制地址' },
  proxyRestart: { en: 'Restart Server', zh: '重启服务' },
  proxyLoadFailed: { en: 'Failed to load proxy groups', zh: '加载代理分组失败' },
  proxySaveFailed: { en: 'Failed to save proxy group', zh: '保存代理分组失败' },
  proxyCopied: { en: 'Proxy URL copied.', zh: '代理地址已复制。' },
  proxyDeleteConfirm: { en: 'Delete this proxy group?', zh: '确定删除该代理分组？' },
  proxyGroupName: { en: 'Group Name', zh: '分组名称' },
  proxyRegex: { en: 'Regex', zh: '正则' },
  proxyMode: { en: 'Mode', zh: '模式' },
  proxyTargetUrl: { en: 'Target URL', zh: '目标地址' },
  proxyPriority: { en: 'Priority', zh: '优先级' },
  proxyEnabled: { en: 'Enabled', zh: '已启用' },
  proxyDisabled: { en: 'Disabled', zh: '已停用' },
  proxyEnable: { en: 'Enable', zh: '启用' },
  proxyDisable: { en: 'Disable', zh: '停用' },
  proxyAutoCapture: { en: 'Auto capture', zh: '自动捕获' },
  proxyManualCapture: { en: 'Manual capture', zh: '手动捕获' },
  proxyLoading: { en: 'Loading proxy groups...', zh: '代理分组加载中...' },
  proxyEmpty: { en: 'No proxy groups yet.', zh: '暂无代理分组。' },

  // Team management
  teamMembersTitle: { en: 'Team Members', zh: '团队成员' },
  teamMembersDesc: {
    en: 'Manage access and permissions for your project collaborators.',
    zh: '管理项目协作者的访问与权限。',
  },
  teamInviteMember: { en: 'Invite Member', zh: '邀请成员' },
  teamAddMember: { en: 'Send Invite', zh: '发送邀请' },
  teamMemberEmailPlaceholder: { en: 'Email address', zh: '邮箱地址' },
  teamFilterPlaceholder: { en: 'Filter members...', zh: '筛选成员...' },
  teamTotal: { en: 'Total:', zh: '共计：' },
  teamRoleLabel: { en: 'Role', zh: '角色' },
  teamStatusLabel: { en: 'Status', zh: '状态' },
  teamStatusActive: { en: 'Active', zh: '活跃' },
  teamStatusInactive: { en: 'Inactive', zh: '停用' },
  teamRoleOwner: { en: 'Owner', zh: '所有者' },
  teamRoleAdmin: { en: 'Admin', zh: '管理员' },
  teamRoleEditor: { en: 'Editor', zh: '编辑者' },
  teamRoleViewer: { en: 'Viewer', zh: '查看者' },
  teamLoading: { en: 'Loading members...', zh: '成员加载中...' },
  teamEmptyTitle: { en: 'No members yet', zh: '暂无成员' },
  teamEmptyDesc: {
    en: 'Invite teammates by email to collaborate on this project.',
    zh: '通过邮箱邀请成员，共同维护当前项目。',
  },
  teamInvitationsTitle: { en: 'Pending Invitations', zh: '待接受邀请' },
  teamMembersTab: { en: 'Members', zh: '成员管理' },
  teamInvitesTab: { en: 'Invitations', zh: '邀请管理' },
  teamRolesTab: { en: 'Roles', zh: '角色权限' },
  teamInvitationsEmpty: { en: 'No pending invitations.', zh: '暂无待接受邀请。' },
  teamInviteCopied: { en: 'Invitation copied.', zh: '邀请信息已复制。' },
  teamCopyInvite: { en: 'Copy Invite', zh: '复制邀请' },
  teamRevokeInvite: { en: 'Revoke', zh: '撤销' },
  teamRevokeConfirm: { en: 'Revoke this invitation?', zh: '确定撤销该邀请？' },
  teamPermissionsTitle: { en: 'Roles & Permissions', zh: '角色与权限' },
  teamPermissionsSave: { en: 'Save Permissions', zh: '保存权限' },
  teamPermissionsSaving: { en: 'Saving...', zh: '保存中...' },
  teamPermissionsSaved: { en: 'Permissions saved.', zh: '权限已保存。' },
  teamPermissionsReadOnly: {
    en: 'Only the project owner can edit permissions.',
    zh: '仅项目所有者可编辑权限。',
  },
  teamCreateRole: { en: 'New Role', zh: '新增角色' },
  teamCopyRole: { en: 'Copy', zh: '复制' },
  teamDeleteRole: { en: 'Delete', zh: '删除' },
  teamDeleteRoleConfirm: {
    en: 'Delete this role? Roles used by members or pending invitations cannot be deleted.',
    zh: '确定删除该角色？已被成员或待接受邀请使用的角色无法删除。',
  },
  teamNewRoleName: { en: 'Custom Role', zh: '自定义角色' },
  teamRoleName: { en: 'Role Name', zh: '角色名称' },
  teamRoleDesc: { en: 'Description', zh: '角色描述' },
  teamRolesEmpty: { en: 'No roles available.', zh: '暂无角色。' },
  teamPermissionGroupProject: { en: 'Project', zh: '项目' },
  teamPermissionGroupApi: { en: 'APIs', zh: '接口' },
  teamPermissionGroupAsset: { en: 'Assets', zh: '公共资产' },
  teamPermissionGroupTeam: { en: 'Team', zh: '团队' },
  teamPermissionGroupRole: { en: 'Roles', zh: '角色权限' },
  permissionProjectView: { en: 'View project', zh: '查看项目' },
  permissionProjectUpdate: { en: 'Edit project', zh: '编辑项目' },
  permissionProjectDelete: { en: 'Delete project', zh: '删除项目' },
  permissionApiView: { en: 'View APIs', zh: '查看接口' },
  permissionApiCreate: { en: 'Create APIs', zh: '新建接口' },
  permissionApiUpdate: { en: 'Edit APIs', zh: '编辑接口' },
  permissionApiDelete: { en: 'Delete APIs', zh: '删除接口' },
  permissionApiProxy: { en: 'Debug or proxy APIs', zh: '调试/代理请求' },
  permissionAssetView: { en: 'View assets', zh: '查看资产' },
  permissionAssetCreate: { en: 'Create assets', zh: '新增资产' },
  permissionAssetUpdate: { en: 'Edit assets', zh: '编辑资产' },
  permissionAssetDelete: { en: 'Delete assets', zh: '删除资产' },
  permissionAssetSuggestionAccept: { en: 'Accept suggested assets', zh: '接受建议资产' },
  permissionAssetSuggestionIgnore: { en: 'Ignore suggested assets', zh: '忽略建议资产' },
  permissionTeamView: { en: 'View members', zh: '查看成员' },
  permissionTeamInvite: { en: 'Invite members', zh: '邀请成员' },
  permissionTeamMemberUpdate: { en: 'Edit member role/status', zh: '编辑成员角色/状态' },
  permissionTeamMemberRemove: { en: 'Remove members', zh: '移除成员' },
  permissionTeamInvitationRevoke: { en: 'Revoke invitations', zh: '撤销邀请' },
  permissionRoleView: { en: 'View role permissions', zh: '查看角色权限' },
  permissionRoleUpdate: { en: 'Edit role permissions', zh: '编辑角色权限' },
  teamAllowed: { en: 'Allowed', zh: '允许' },
  teamDenied: { en: 'Denied', zh: '不允许' },
  teamInviteAcceptHint: {
    en: 'Unregistered users can sign up from the invite link and join automatically.',
    zh: '未注册用户可通过邀请链接注册，并自动加入当前项目。',
  },
  teamLoadFailed: { en: 'Failed to load team members', zh: '加载团队成员失败' },
  teamSaveFailed: { en: 'Failed to save member changes', zh: '保存成员变更失败' },
  teamRemove: { en: 'Remove', zh: '移除' },
  teamRemoveConfirm: { en: 'Remove this member?', zh: '确定移除该成员？' },
  teamNoPermission: {
    en: 'Only Owner or Admin can manage members.',
    zh: '仅所有者或管理员可管理成员。',
  },

  // Project management
  projectsDesc: {
    en: 'Manage your development environments and team access.',
    zh: '管理开发环境及团队访问权限。',
  },
  projectsEnter: { en: 'Enter', zh: '进入' },
  projectsLoading: { en: 'Loading projects...', zh: '项目加载中...' },
  projectsLoadError: { en: 'Failed to load project list', zh: '加载项目列表失败' },
  projectsNetworkError: {
    en: 'Network error, unable to load project list',
    zh: '网络异常，无法加载项目列表',
  },
  projectNoDescription: { en: 'No description', zh: '暂无描述' },
  projectStatusActive: { en: 'Active', zh: '活跃' },
  projectCurrentUser: { en: 'You', zh: '你' },
  projectRename: { en: 'Rename', zh: '重命名' },
  projectRenamePrompt: { en: 'Rename project', zh: '重命名项目' },
  projectRenameFailed: { en: 'Network error, rename failed', zh: '网络异常，重命名失败' },
  projectDelete: { en: 'Delete', zh: '删除' },
  projectDeleteConfirm: {
    en: 'Are you sure you want to delete this project?',
    zh: '确定要删除该项目吗？',
  },
  projectDeleteFailed: { en: 'Network error, delete failed', zh: '网络异常，删除失败' },

  // Mock editor
  mockEditorTitle: { en: 'Edit Mock Data', zh: '编辑 Mock 数据' },
  mockEditorJsonTab: { en: 'JSON', zh: 'JSON' },
  mockEditorScriptTab: { en: 'SCRIPT', zh: '脚本' },
  mockEditorCopy: { en: 'Copy', zh: '复制' },
  mockEditorCopied: { en: 'Copied', zh: '已复制' },
  mockEditorTestRun: { en: 'Test Run', zh: '测试运行' },
  mockEditorLastSaved: {
    en: 'Last saved: Today at 14:22',
    zh: '上次保存：今天 14:22',
  },
  mockEditorCancel: { en: 'Cancel', zh: '取消' },
  mockEditorSaveChanges: { en: 'Save Changes', zh: '保存修改' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
